#!/bin/bash

make manifest GLUON_BRANCH=experimental
./contrib/sign.sh ~/secret images/sysupgrade/experimental.manifest 
./contrib/sign.sh ~/secret images/factory/experimental.manifest 

d=`date`

mkdir "/var/www/gluon/experimental.$d"
cp images/* "/var/www/gluon/experimental.$d"

rm experimental
ln -s "/var/www/gluon/experimental.$d" experimental
